gh-pages:
  stage: build
  before_script:
    - apk add --update openssh-client
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.email "noreply"
    - git config --global user.name "Gitlab CI"
  script:
    - ls
    - git
