# See https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  DOCKER_REGISTRY_IMAGE: "haopoboy/docmd"
  
cache:
  paths:
    - .m2/repository
    - target

.validate: &validate
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean test-compile

.npm: &npm
  stage: build
  before_script:
    - cd frontend
  script:
    - node -v
    - npm -v
    - npm install
    - npm run build
    
.test: &test
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

.verify: &verify
  stage: test
  script:
    - ./mvnw -v
    - ls -al frontend
    - ls -al target

# Branch name is for the tag of docker image
.deploy: &deploy
  stage: deploy
  script:
    - docker build --pull -t "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$DOCKER_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  except:
    - master

# Master is the latest tag of docker image
.deploy-master: &deploy
  stage: deploy
  script:
    - docker build --pull -t "$DOCKER_REGISTRY_IMAGE" .
    - docker push "$DOCKER_REGISTRY_IMAGE"
  only:
    - master


# Validate using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.5-jdk-8-alpine

# Validate frontend using Node8
npm:node8:
  <<: *npm
  image: node:8-alpine
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week

# Validate frontend using Node10 just for test
npm:node10:
  <<: *npm
  image: node:10-alpine

# Test using JDK8
test:jdk8:
  <<: *test
  image: maven:3.5-jdk-8-alpine

# Verify using JDK8 and pack it with frontend of node8
verify:jdk8:
  <<: *verify
  image: maven:3.5-jdk-8-alpine
  artifacts:
    paths:
      - target/package.log
    expire_in: 1 week
  dependencies:
    - npm:node8
    
# Build and deploy jdk8 artifact to Docker Hub
deploy:jdk8:
  <<: *deploy
  image: docker:git
  services:
    - docker:dind
  dependencies:
    - verify:jdk8
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
