gh-pages:
  image: alpine/git
  before_script:
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.email "noreply"
    - git config --global user.name "Gitlab CI"
  script:
    - git --help
    
