# See https://gitlab.com/gitlab-org/gitlab-ce/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  
cache:
  paths:
    - .m2/repository
    - target

.validate: &validate
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean test-compile
    
.test: &test
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

.npm: &npm
  stage: build
  before_script:
    - cd frontend
  script:
    - node -v
    - npm -v
    - npm install
    - npm run build

.verify: &verify
  stage: test
  script:
    - ./mvnw -v
    - ls -al frontend
    - ls -al target

# Validate using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.5-jdk-8-alpine

# Validate frontend using Node8
npm:node8:
  <<: *npm
  image: node:8-alpine
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week

# Validate frontend using Node10 just for test
npm:node10:
  <<: *npm
  image: node:10-alpine

# Test using JDK8
test:jdk8:
  <<: *test
  image: maven:3.5-jdk-8-alpine

# Verify using JDK8 and pack it with frontend of node8
verify:jdk8:
  <<: *verify
  image: maven:3.5-jdk-8-alpine
  artifacts:
    paths:
      - target/package.log
    expire_in: 1 week
  dependencies:
    - npm:node8
