cache:
  paths:
    - .m2/repository
    - target

.validate: &validate
  stage: build
  script:
    - ./mvnw -v
    - ./mvnw clean test-compile
    
.test: &test
  stage: test
  script:
    - ./mvnw -v
    - ./mvnw test

.npm: &npm
  stage: build
  before_script:
    - cd frontend
  script:
    - node -v
    - npm -v
    - npm install
    - npm run build

.verify: &verify
  stage: test
  script:
    - ./mvnw -v
    - ls -al frontend
    - ls -al target

# Validate using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.5-jdk-8-alpine

# Validate frontend using Node8
npm:node8:
  <<: *npm
  image: node:8-alpine
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 week

# Validate frontend using Node10 just for test
npm:node10:
  <<: *npm
  image: node:10-alpine

# Test using JDK8
test:jdk8:
  <<: *test
  image: maven:3.5-jdk-8-alpine

# Verify using JDK8 and pack it with frontend of node8
verify:jdk8:
  <<: *verify
  image: maven:3.5-jdk-8-alpine
  artifacts:
    paths:
      - target/package.log
    expire_in: 1 week
  dependencies:
    - npm:node8
